-- (a) find the total number of customers by country

SELECT
	country,
	COUNT(DISTINCT customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY country;

-- (b) find the total number of customers by gender

SELECT
	gender,
	COUNT(DISTINCT customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY gender;

-- (c) find the total number of products by category

SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category;

-- (d) what is the average cost in each category?

SELECT
	category,
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category;

-- (e) what is the total revenue generated for each category?

SELECT
	p.category,
	SUM(s.sales) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- (f) what is the total revenue generated by each customer?

SELECT TOP 5
	c.customer_key,
	c.first_name,
	SUM(s.sales) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = s.customer_key
GROUP BY c.customer_key,c.first_name
ORDER BY total_revenue DESC;
